env:
  browser: true
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
parser: '@typescript-eslint/parser'
ignorePatterns:
  - dist/*
  - node_modules/*
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-module-boundary-types': off
  no-mixed-spaces-and-tabs: off
